name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & Run tests
        run: mvn clean test -Dtest=com.checkIn.runners.TestRunner

      - name: Upload test reports and evidences
        uses: actions/upload-artifact@v3
        with:
          name: evidencias-checkin
          path: |
            target/cucumber-reports/**
            src/test/resources/evidencias/**
